### ISSUE TITLE
Password requirements

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/kaspa-wallet#24]
- [ ] Passwords should conform to the following regex `“^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,}$”`.
- [ ] The password field should display the hint "At least 8 characters, one capital, one lower and one number”
- [ ] Button should not be clickable until the entry meets the criteria
- [ ] Starting with [this list](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt), filter all that would be rejected by the regex anyway, and then include the list so as to explicitly reject any passwords that are on it. Error message for a match should read "This password is not permitted."

**Comment by mds1** [comment]
Some specific implementation questions:

1. Do we want the hint on all password fields, or just the create password fields? I think the former, as it can serve as a reminder if a user forgets their password
2. Do we want the "button should not be clickable until entry meets the criteria" on all password fields, or just the create password fields? I think again think the former for consistency

I don't feel strongly about this so am fine with either option

**Comment by mds1** [comment]
Also, are we set on this regex? It does not seem ideal. For example `7w3n8@t7kuxN` does not match (and therefore would not be accepted) because of the `@` in the middle, but it does match if you remove the `@`

**Comment by mds1** [comment]
Also worth noting—none of the passwords on that list match the regex, so I don't think we need to bother including the list

**Comment by apbendi** [comment]
Good catch on that, I don't think this regex is ideal. Let's go with this one:

`"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"`

Via https://stackoverflow.com/a/21456918

Described as "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character".

If none of those passwords match, then just ignore that requirement.

**Comment by mds1** [comment]
Some notes on how this issue will be resolved in #42:

1. The password hint of "At least 8 characters, one capital, one lower, one number, and one symbol" shows on *all* password fields (by "all" I mean "create" password fields + "unlock" password fields)
2. The "button should not be clickable until entry meets the criteria" requirement is also true on *all* password fields
3. The regex was updated to `^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$` because this one includes a few extra symbols. For example, the one @apbendi shared above would not match `Qq1!q#qqq` because `#` is not a supported character. [Source](https://stackoverflow.com/a/19605207/10152004) of this new regex
4. No password in the "most popular password" list meets these requirements, so the list is not used
